konveyor/tackle2-addon-windup

Dockerfile, README.md, cmd/command.go, cmd/git.go, cmd/main.go, cmd/mvn.go, cmd/repository.go, cmd/windup.go, go.mod, go.sum, hack/application.sh, hack/secret.json, hack/task.sh
Integration with hub:
- repositories: github only.
- credentials
- maven
- windup options
Enhanced addon data to include options.
Integration with /mnt/m2 shared volume for the maven m2 repostory.
=> Integration with hub, credentials, repositories and maven.

README.md
- Display status of quay image on repo
=> Add quay.io image status badge

cmd/command.go, cmd/git.go, cmd/main.go, cmd/mvn.go, cmd/repository.go, cmd/svn.go, go.mod, go.sum
Add git:
- proxy integration
- SSH credentials support.
- global git settings integration.
Add SVN support.
=> Add Git proxy integration.

Dockerfile
=> Using windup 5.3.0-SNAPSHOT

Dockerfile, cmd/windup.go
Windup 5.3.0 requires java 11.
=> Windup requires java-11.

cmd/mvn.go, cmd/windup.go, go.mod, go.sum, hack/secret.json
Maven `settings.xml` should be optional.
Pass options to maven to support insecure access (self signed certificates).
Unrelated: Fix windup using uploaded custom rules files.
=> Maven settings optional; add insecure settings.

cmd/command.go, cmd/git.go, cmd/main.go, cmd/mvn.go, cmd/repository.go, cmd/svn.go, cmd/windup.go, go.mod
Improved error handling:
- Wrap errors at the edge.
- Return _SoftError_ where appropriate.
- Note credentials and proxies used.
=> Improved error handling.

cmd/command.go, cmd/git.go, cmd/main.go, cmd/mvn.go, cmd/svn.go, cmd/windup.go, go.mod, go.sum
Fix issues with binary analysis.
Replaces `os.RemoveAll()` with `rm -rf <path>` for MUCH better performance on network storage.
Update adapter (hub) lib.
=> Fix binary.

cmd/repository.go
Using explicit application repository kinds rather then determining using URL.
=> Using explicit application repository kinds.

cmd/command.go, cmd/windup.go
Append the mta.log when windup fails.
Report ExitError.
=> Improved error reporting.

cmd/main.go
https://issues.redhat.com/browse/TACKLE-605?filter=12394638
=> Adjust source & dependencies directory.

cmd/main.go
https://issues.redhat.com/browse/TACKLE-628
=> TACKLE-628: Fix SEGV when Repository is nil.

go.mod, go.sum
Deps updated: hub and addon main to include key formatting and fix no-pass keys.
=> SSH fixes.

Dockerfile
Package with windup 6.0.0 FINAL with DiVA support.
https://issues.redhat.com/browse/TACKLE-697
=> TACKLE-697: Package with windup 6.0.0.

go.mod, go.sum
Latest addon with relaxed file exists.
https://issues.redhat.com/browse/TACKLE-751
=> TACKLE-751 - Latest addon with relaxed file exists.

.github/workflows/test-windup.yml, Makefile, README.md, hack/test-e2e.sh
- Perform various build steps when new changes are pushed or a pull request is created on main branch
- Build the windup image
- Runs end-to-end test by deploying the new changes on a Minikube cluster
=> Workflow to test windup addon

go.mod, go.sum
Ref https://github.com/konveyor/tackle2-addon/pull/17 and https://issues.redhat.com/browse/TACKLE-828
=> Tackle-828: Latest addon with command RunWith() and RunSilentWith().

.github/actions/test-e2e-windup/action.yml, .github/workflows/test-windup.yml, Makefile, hack/test-e2e.sh
Signed-off-by: Ankur Mundra <amundra@redhat.com>
=> test-e2e as a composite action

Dockerfile
- See #66 for details
Signed-off-by: Franco Bladilo <fbladilo@redhat.com>
=> Backport: Update windup to 6.1.0

Dockerfile
- Sync with final build of windup 6.1.0
- Needs backport v2.1.2
=> Update windup 6.1.0 final

Dockerfile
- See #69
Signed-off-by: Franco Bladilo <fbladilo@redhat.com>
=> Backport update windup 6.1.0 final

Dockerfile
Signed-off-by: Jason Montleon <jmontleo@redhat.com>
=> :bug: Use standard EL9 SVN package

.github/workflows/verifyPR.yml
Want to ensure that commits to this project conform to our title guidelines specified in https://github.com/konveyor/release-tools/blob/main/VERSIONING.md
=> :seedling: Add PR checks

cmd/windup.go
=> :sparkles: Support export CSV.

cmd/windup.go
Resolves 2 problems:
The Windup CLI requires it be passed at least one `--target` parameter.  When analysis is performed using only rules files defined in repository(s), this can result in the task.Data list of targets to be empty because the UI does not know anything about the files in the git repositories.  Long term, windup needs to stop requiring the --target.  However, as a work-around, the addon will inject an empty rule file (no rules) with a target of `Empty` and list it as `--target Empty` to make windup happy.
A RuleSet (defined in rules files) may define a `targetTechnology` but it's not required. When a target is defined, it must match a `--target` for the rules to be executed.  When a target is not defined, the rules are executed unconditionally.
For rule files in a …
=> :sparkles: Ensure at least 1 target.

Dockerfile, cmd/windup.go
=> :sparkles: windup 6.2.4.

Dockerfile
=> :bug: Windup 6.2.5.

Dockerfile
=> :sparkles: windup 6.3.2.
